# Generated by Django 5.1.3 on 2024-11-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("傳統技藝", "傳統技藝"),
                    ("歷史文化", "歷史文化"),
                    ("佳餚食譜", "佳餚食譜"),
                    ("科技新知", "科技新知"),
                    ("人生經驗", "人生經驗"),
                    ("其他", "其他"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[
                    ("傳統技藝", "傳統技藝"),
                    ("歷史文化", "歷史文化"),
                    ("佳餚食譜", "佳餚食譜"),
                    ("科技新知", "科技新知"),
                    ("人生經驗", "人生經驗"),
                    ("其他", "其他"),
                ],
                max_length=50,
            ),
        ),
    ]
