# Generated by Django 5.1.3 on 2024-11-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(default="idle", max_length=10),
        ),
        migrations.AlterField(
            model_name="question",
            name="asker_group",
            field=models.CharField(
                choices=[("青世代", "青世代"), ("銀世代", "銀世代")], max_length=10
            ),
        ),
    ]
