# Generated by Django 5.1.3 on 2024-11-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_alter_article_category_alter_question_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="liked_by",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
