# Generated by Django 5.1.3 on 2024-11-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_article_website_url_alter_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
