# Generated by Django 5.1.3 on 2024-11-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='website_url',
        ),
        migrations.AddField(
            model_name='article',
            name='input_text',
            field=models.TextField(default=''),
        ),
    ]
